AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Homex Demo API

Parameters:
  DomainName:
    Type: String
    Default: api.homexcloud.com
  HostedZoneName:
    Type: String
    Default: homexcloud.com

Resources:
  HomexDemoAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: nodejs8.10
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Events:
        helloWorldAPI:
          Type: Api
          Properties:
            Path: /demoapi
            Method: get
      Environment:
        Variables:
          REGION: us-west-2

  BasePathMapping:
    DependsOn: HomexDemoAPI
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: 'demoapi'
      DomainName: 'api.homexcloud.com'
      RestApiId:
        Ref: ServerlessRestApi
      Stage:
        Ref: ServerlessRestApiProdStage
