AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda

Parameters:
  DomainName:
    Type: String
    Default: api.homexcloud.com
  HostedZoneName:
    Type: String
    Default: homexcloud.com

Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: nodejs8.10
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Events:
        helloWorldAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          REGION: us-west-2

  APIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: arn:aws:acm:us-west-2:620169180577:certificate/75622831-3589-47df-9fb6-5d6c2d0e7da4
      DomainName: !Ref DomainName

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref APIDomainName
      RestApiId: !Ref ServerlessRestApi
      Stage: Prod
