AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: HomexCloud Demo API

Parameters:
  DomainName:
    Type: String
    Default: api.homexcloud.com
  HostedZoneName:
    Type: String
    Default: homexcloud.com
  StageName:
    Type: String
    Default: dev
    Description: The Lambda Function and API Gateway Stage
  FunctionName:
    Type: String
    Default: getLocation
    Description: The Lambda Function Name

Resources:
  HomexCloudDemoAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: nodejs8.10
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          STAGE: !Ref StageName
          REGION: us-west-2
      Events:
        locationAPIRequest:
          Type: Api
          Properties:
            Path: /location
            Method: post
            Cors: true
            RestApiId:
              Ref: locationAPI

  BasePathMapping:
    DependsOn: HomexCloudDemoAPI
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      BasePath: 'demo'
      DomainName: 'api.homexcloud.com'
      RestApiId:
        Ref: locationAPI
      Stage:
        Ref: locationAPIStage

  locationAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: !Ref StageName
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Sub HomexCloud-${FunctionName}
        paths:
          /location:
            post:
              x-amazon-apigateway-integration:
                uri:
                  !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HomexCloudDemoAPI.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws